In [108]:
import augur

# import everything from githubapi.py and ghtorrent.py so we can
# just copy and paste our function later
import json
import re
from dateutil.parser import parse
import pandas as pd
import github
import numpy as np
import sqlalchemy as s
import datetime
import requests

%matplotlib inline
# create an Augur application so we can test our function
augurApp = augur.Application('../augur.cfg')
github = augurApp.github()
ghtorrent = augurApp.ghtorrent()

In [109]:
df = ghtorrent.issue_comment_time('rails', 'rails')

In [110]:
df['opened'] = pd.to_datetime(df['opened'],errors='coerce')
df = df.set_index(['opened'])
df = df.dropna()

/Users/howderek/anaconda3/envs/augur/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                      id  pull_request  minutes_to_comment
opened
2009-04-05  1.366260e+05      0.000000        22716.000000
2009-04-12           NaN           NaN                 NaN
2009-04-19  1.366250e+05      0.000000           41.000000
2009-04-26           NaN           NaN                 NaN
2009-05-03  1.366240e+05      0.000000            5.000000
2009-05-10           NaN           NaN                 NaN
2009-05-17           NaN           NaN                 NaN
2009-05-24           NaN           NaN                 NaN
2009-05-31           NaN           NaN                 NaN
2009-06-07           NaN           NaN                 NaN
2009-06-14           NaN           NaN                 NaN
2009-06-21           NaN           NaN                 NaN
2009-06-28           NaN           NaN                 NaN
2009-07-05           NaN           NaN                 NaN
2009-07-12           NaN           NaN                 NaN
2009-07-19           NaN           NaN                 NaN
2009-07-26           NaN           NaN                 NaN
2009-08-02           NaN           NaN                 NaN
2009-08-09           NaN           NaN                 NaN
2009-08-16           NaN           NaN                 NaN
2009-08-23           NaN           NaN                 NaN
2009-08-30           NaN           NaN                 NaN
2009-09-06           NaN           NaN                 NaN
2009-09-13           NaN           NaN                 NaN
2009-09-20           NaN           NaN                 NaN
2009-09-27           NaN           NaN                 NaN
2009-10-04           NaN           NaN                 NaN
2009-10-11           NaN           NaN                 NaN
2009-10-18           NaN           NaN                 NaN
2009-10-25           NaN           NaN                 NaN
...                  ...           ...                 ...
2017-02-12  4.378245e+07      0.676923          815.235294
2017-02-19  4.419240e+07      0.659794         4234.700000
2017-02-26  4.463189e+07      0.696721         2724.100000
2017-03-05  4.501469e+07      0.605505         3807.450000
2017-03-12  4.542362e+07      0.614583         3435.227273
2017-03-19  4.587048e+07      0.630435         5906.461538
2017-03-26  4.627955e+07      0.554348         5003.078431
2017-04-02  4.674666e+07      0.690141         3679.137931
2017-04-09  4.715501e+07      0.597222         3997.459459
2017-04-16  4.757452e+07      0.600000         2055.781250
2017-04-23  4.797449e+07      0.602740         5236.333333
2017-04-30  4.835881e+07      0.645833         4148.369565
2017-05-07  4.876544e+07      0.565217         1619.700000
2017-05-14  4.921758e+07      0.480000         2083.434783
2017-05-21  4.960281e+07      0.631579         2998.857143
2017-05-28  5.004163e+07      0.666667         2731.571429
2017-06-04  5.032022e+07      0.747368         3386.404762
2017-06-11  5.074241e+07      0.684932         7817.344828
2017-06-18  5.114025e+07      0.573333         2420.848485
2017-06-25  5.156680e+07      0.666667         3295.292683
2017-07-02  5.193815e+07      0.733333         2831.047619
2017-07-09  5.234533e+07      0.679487         1322.114286
2017-07-16  5.275733e+07      0.764045         2490.281250
2017-07-23  5.314798e+07      0.686047         2552.666667
2017-07-30  5.353208e+07      0.757009         1834.900000
2017-08-06  5.397232e+07      0.750000         1020.473684
2017-08-13  5.437936e+07      0.784173          911.290909
2017-08-20  5.477579e+07      0.800000          760.769231
2017-08-27  5.518430e+07      0.808081          828.064516
2017-09-03  5.552484e+07      0.631579          606.750000

[440 rows x 3 columns]

In [111]:
dfnew = df.resample('W-MON').mean()
dfnew

                      id  pull_request  minutes_to_comment
opened
2009-04-06  1.366260e+05      0.000000        22716.000000
2009-04-13           NaN           NaN                 NaN
2009-04-20  1.366250e+05      0.000000           41.000000
2009-04-27           NaN           NaN                 NaN
2009-05-04  1.366240e+05      0.000000            5.000000
2009-05-11           NaN           NaN                 NaN
2009-05-18           NaN           NaN                 NaN
2009-05-25           NaN           NaN                 NaN
2009-06-01           NaN           NaN                 NaN
2009-06-08           NaN           NaN                 NaN
2009-06-15           NaN           NaN                 NaN
2009-06-22           NaN           NaN                 NaN
2009-06-29           NaN           NaN                 NaN
2009-07-06           NaN           NaN                 NaN
2009-07-13           NaN           NaN                 NaN
2009-07-20           NaN           NaN                 NaN
2009-07-27           NaN           NaN                 NaN
2009-08-03           NaN           NaN                 NaN
2009-08-10           NaN           NaN                 NaN
2009-08-17           NaN           NaN                 NaN
2009-08-24           NaN           NaN                 NaN
2009-08-31           NaN           NaN                 NaN
2009-09-07           NaN           NaN                 NaN
2009-09-14           NaN           NaN                 NaN
2009-09-21           NaN           NaN                 NaN
2009-09-28           NaN           NaN                 NaN
2009-10-05           NaN           NaN                 NaN
2009-10-12           NaN           NaN                 NaN
2009-10-19           NaN           NaN                 NaN
2009-10-26           NaN           NaN                 NaN
...                  ...           ...                 ...
2017-02-13  4.381915e+07      0.406250          577.562500
2017-02-20  4.421677e+07      0.236842         4547.131579
2017-02-27  4.468356e+07      0.420290         2927.550725
2017-03-06  4.507571e+07      0.254545         4284.654545
2017-03-13  4.548692e+07      0.186047         2426.883721
2017-03-20  4.593249e+07      0.232558         6276.139535
2017-03-27  4.631254e+07      0.204545         4869.454545
2017-04-03  4.677474e+07      0.218750         3940.531250
2017-04-10  4.721241e+07      0.324324         3617.135135
2017-04-17  4.765612e+07      0.375000         1930.343750
2017-04-24  4.803590e+07      0.357143         6072.380952
2017-05-01  4.838499e+07      0.225000         3444.550000
2017-05-08  4.882233e+07      0.133333         1956.766667
2017-05-15  4.924760e+07      0.229167         1961.145833
2017-05-22  4.964300e+07      0.255814         2756.139535
2017-05-29  5.014904e+07      0.315789         2660.789474
2017-06-05  5.035645e+07      0.485714         3874.285714
2017-06-12  5.078075e+07      0.233333         7716.900000
2017-06-19  5.116883e+07      0.272727         2288.151515
2017-06-26  5.160482e+07      0.348837         3163.023256
2017-07-03  5.197491e+07      0.512821         3098.487179
2017-07-10  5.238399e+07      0.275000         1234.750000
2017-07-17  5.278784e+07      0.448276         2538.586207
2017-07-24  5.322183e+07      0.377778         2251.911111
2017-07-31  5.361227e+07      0.541667         1929.312500
2017-08-07  5.405356e+07      0.487179         1012.076923
2017-08-14  5.441325e+07      0.450980          930.254902
2017-08-21  5.483853e+07      0.555556          803.861111
2017-08-28  5.523528e+07      0.500000          881.777778
2017-09-04  5.559050e+07      0.222222          368.000000

[440 rows x 3 columns]

In [113]:
dfnew.fillna(0)

                      id  pull_request  minutes_to_comment
opened
2009-04-06  1.366260e+05      0.000000        22716.000000
2009-04-13  0.000000e+00      0.000000            0.000000
2009-04-20  1.366250e+05      0.000000           41.000000
2009-04-27  0.000000e+00      0.000000            0.000000
2009-05-04  1.366240e+05      0.000000            5.000000
2009-05-11  0.000000e+00      0.000000            0.000000
2009-05-18  0.000000e+00      0.000000            0.000000
2009-05-25  0.000000e+00      0.000000            0.000000
2009-06-01  0.000000e+00      0.000000            0.000000
2009-06-08  0.000000e+00      0.000000            0.000000
2009-06-15  0.000000e+00      0.000000            0.000000
2009-06-22  0.000000e+00      0.000000            0.000000
2009-06-29  0.000000e+00      0.000000            0.000000
2009-07-06  0.000000e+00      0.000000            0.000000
2009-07-13  0.000000e+00      0.000000            0.000000
2009-07-20  0.000000e+00      0.000000            0.000000
2009-07-27  0.000000e+00      0.000000            0.000000
2009-08-03  0.000000e+00      0.000000            0.000000
2009-08-10  0.000000e+00      0.000000            0.000000
2009-08-17  0.000000e+00      0.000000            0.000000
2009-08-24  0.000000e+00      0.000000            0.000000
2009-08-31  0.000000e+00      0.000000            0.000000
2009-09-07  0.000000e+00      0.000000            0.000000
2009-09-14  0.000000e+00      0.000000            0.000000
2009-09-21  0.000000e+00      0.000000            0.000000
2009-09-28  0.000000e+00      0.000000            0.000000
2009-10-05  0.000000e+00      0.000000            0.000000
2009-10-12  0.000000e+00      0.000000            0.000000
2009-10-19  0.000000e+00      0.000000            0.000000
2009-10-26  0.000000e+00      0.000000            0.000000
...                  ...           ...                 ...
2017-02-13  4.381915e+07      0.406250          577.562500
2017-02-20  4.421677e+07      0.236842         4547.131579
2017-02-27  4.468356e+07      0.420290         2927.550725
2017-03-06  4.507571e+07      0.254545         4284.654545
2017-03-13  4.548692e+07      0.186047         2426.883721
2017-03-20  4.593249e+07      0.232558         6276.139535
2017-03-27  4.631254e+07      0.204545         4869.454545
2017-04-03  4.677474e+07      0.218750         3940.531250
2017-04-10  4.721241e+07      0.324324         3617.135135
2017-04-17  4.765612e+07      0.375000         1930.343750
2017-04-24  4.803590e+07      0.357143         6072.380952
2017-05-01  4.838499e+07      0.225000         3444.550000
2017-05-08  4.882233e+07      0.133333         1956.766667
2017-05-15  4.924760e+07      0.229167         1961.145833
2017-05-22  4.964300e+07      0.255814         2756.139535
2017-05-29  5.014904e+07      0.315789         2660.789474
2017-06-05  5.035645e+07      0.485714         3874.285714
2017-06-12  5.078075e+07      0.233333         7716.900000
2017-06-19  5.116883e+07      0.272727         2288.151515
2017-06-26  5.160482e+07      0.348837         3163.023256
2017-07-03  5.197491e+07      0.512821         3098.487179
2017-07-10  5.238399e+07      0.275000         1234.750000
2017-07-17  5.278784e+07      0.448276         2538.586207
2017-07-24  5.322183e+07      0.377778         2251.911111
2017-07-31  5.361227e+07      0.541667         1929.312500
2017-08-07  5.405356e+07      0.487179         1012.076923
2017-08-14  5.441325e+07      0.450980          930.254902
2017-08-21  5.483853e+07      0.555556          803.861111
2017-08-28  5.523528e+07      0.500000          881.777778
2017-09-04  5.559050e+07      0.222222          368.000000

[440 rows x 3 columns]

In [114]:
dfnew

                      id  pull_request  minutes_to_comment
opened
2009-04-06  1.366260e+05      0.000000        22716.000000
2009-04-13           NaN           NaN                 NaN
2009-04-20  1.366250e+05      0.000000           41.000000
2009-04-27           NaN           NaN                 NaN
2009-05-04  1.366240e+05      0.000000            5.000000
2009-05-11           NaN           NaN                 NaN
2009-05-18           NaN           NaN                 NaN
2009-05-25           NaN           NaN                 NaN
2009-06-01           NaN           NaN                 NaN
2009-06-08           NaN           NaN                 NaN
2009-06-15           NaN           NaN                 NaN
2009-06-22           NaN           NaN                 NaN
2009-06-29           NaN           NaN                 NaN
2009-07-06           NaN           NaN                 NaN
2009-07-13           NaN           NaN                 NaN
2009-07-20           NaN           NaN                 NaN
2009-07-27           NaN           NaN                 NaN
2009-08-03           NaN           NaN                 NaN
2009-08-10           NaN           NaN                 NaN
2009-08-17           NaN           NaN                 NaN
2009-08-24           NaN           NaN                 NaN
2009-08-31           NaN           NaN                 NaN
2009-09-07           NaN           NaN                 NaN
2009-09-14           NaN           NaN                 NaN
2009-09-21           NaN           NaN                 NaN
2009-09-28           NaN           NaN                 NaN
2009-10-05           NaN           NaN                 NaN
2009-10-12           NaN           NaN                 NaN
2009-10-19           NaN           NaN                 NaN
2009-10-26           NaN           NaN                 NaN
...                  ...           ...                 ...
2017-02-13  4.381915e+07      0.406250          577.562500
2017-02-20  4.421677e+07      0.236842         4547.131579
2017-02-27  4.468356e+07      0.420290         2927.550725
2017-03-06  4.507571e+07      0.254545         4284.654545
2017-03-13  4.548692e+07      0.186047         2426.883721
2017-03-20  4.593249e+07      0.232558         6276.139535
2017-03-27  4.631254e+07      0.204545         4869.454545
2017-04-03  4.677474e+07      0.218750         3940.531250
2017-04-10  4.721241e+07      0.324324         3617.135135
2017-04-17  4.765612e+07      0.375000         1930.343750
2017-04-24  4.803590e+07      0.357143         6072.380952
2017-05-01  4.838499e+07      0.225000         3444.550000
2017-05-08  4.882233e+07      0.133333         1956.766667
2017-05-15  4.924760e+07      0.229167         1961.145833
2017-05-22  4.964300e+07      0.255814         2756.139535
2017-05-29  5.014904e+07      0.315789         2660.789474
2017-06-05  5.035645e+07      0.485714         3874.285714
2017-06-12  5.078075e+07      0.233333         7716.900000
2017-06-19  5.116883e+07      0.272727         2288.151515
2017-06-26  5.160482e+07      0.348837         3163.023256
2017-07-03  5.197491e+07      0.512821         3098.487179
2017-07-10  5.238399e+07      0.275000         1234.750000
2017-07-17  5.278784e+07      0.448276         2538.586207
2017-07-24  5.322183e+07      0.377778         2251.911111
2017-07-31  5.361227e+07      0.541667         1929.312500
2017-08-07  5.405356e+07      0.487179         1012.076923
2017-08-14  5.441325e+07      0.450980          930.254902
2017-08-21  5.483853e+07      0.555556          803.861111
2017-08-28  5.523528e+07      0.500000          881.777778
2017-09-04  5.559050e+07      0.222222          368.000000

[440 rows x 3 columns]