In [3]:
import augur

# import everything from githubapi.py and ghtorrent.py so we can
# just copy and paste our function later
import json
import re
from dateutil.parser import parse
import pandas as pd
import github
import numpy as np
import sqlalchemy as s
import datetime
import requests

%matplotlib inline
# create an Augur application so we can test our function
augurApp = augur.Application('../augur.cfg')
github = augurApp.github()
ghtorrent = augurApp.ghtorrent()

In [14]:
df = ghtorrent.issue_comment_time('rails', 'rails')
df

,id,opened,first_commented,pull_request,minutes_to_comment
0,2,2012-01-19 05:24:55,2012-01-19 05:30:13,0,5.0
1,3,2012-01-26 15:07:56,2012-01-26 15:09:28,0,1.0
2,4,2012-01-26 15:20:54,2012-02-02 20:58:26,0,10417.0
3,5,2012-01-26 15:37:31,2012-01-26 16:01:18,0,23.0
4,6,2012-01-26 16:28:33,2012-01-28 12:25:55,0,2637.0
5,7,2012-01-25 05:24:41,2012-01-25 16:24:26,0,659.0
6,8,2012-01-25 00:22:20,2012-01-25 00:29:26,0,7.0
7,9,2012-01-26 17:18:23,2012-01-26 20:04:45,0,166.0
8,10,2012-01-26 17:35:50,2012-01-27 08:47:57,0,912.0
9,11,2012-01-26 17:50:28,NaT,0,NaN
10,12,2012-01-26 03:07:34,2012-01-26 12:17:26,0,549.0
11,13,2012-01-26 19:31:48,2012-01-26 19:35:18,0,3.0
12,14,2012-01-26 11:32:48,2012-01-26 14:39:35,0,186.0
13,15,2012-01-26 22:27:26,2012-01-26 23:11:46,0,44.0
14,16,2012-01-20 18:17:04,2012-01-20 19:46:14,0,89.0
15,17,2012-01-27 04:30:24,2012-01-27 05:21:48,0,51.0
16,18,2012-01-27 06:36:18,2012-01-27 15:56:29,0,560.0
17,19,2012-01-27 07:20:24,2012-04-29 17:41:35,0,134541.0
18,20,2012-01-27 12:18:16,2012-01-27 15:53:16,0,215.0
19,21,2012-01-27 13:53:02,2012-01-28 17:46:31,0,1673.0
20,22,2012-01-27 15:43:10,2012-03-12 11:05:05,0,64521.0
21,23,2012-01-19 22:48:36,2012-01-20 17:17:08,0,1108.0
22,24,2012-01-27 19:50:57,2012-02-01 15:15:39,0,6924.0
23,25,2012-01-28 08:44:02,2012-01-28 09:01:58,0,17.0
24,26,2012-01-25 11:07:03,2012-01-25 16:18:47,0,311.0
25,28,2012-01-28 19:22:57,2012-01-28 19:53:23,0,30.0
26,29,2012-01-28 20:15:28,2012-01-30 11:00:06,0,2324.0
27,30,2012-01-30 02:39:04,2012-01-30 20:28:50,0,1069.0
28,31,2012-01-30 05:20:00,2012-01-30 05:28:17,0,8.0
29,32,2012-01-30 05:28:53,2012-01-30 07:05:27,0,96.0
...,...,...,...,...,...
31241,55447333,2017-08-29 00:00:18,NaT,1,NaN
31242,55447830,2017-08-29 00:13:03,NaT,1,NaN
31243,55462578,2017-08-29 07:52:56,NaT,1,NaN
31244,55468768,2017-08-29 09:54:09,NaT,1,NaN
31245,55469365,2017-08-29 10:05:17,NaT,1,NaN
31246,55469487,2017-08-29 10:07:11,NaT,1,NaN
31247,55470588,2017-08-29 10:30:44,NaT,1,NaN
31248,55497851,2017-08-29 17:47:00,NaT,1,NaN
31249,55500568,2017-08-29 18:34:07,NaT,1,NaN
31250,55504970,2017-08-29 19:48:50,2017-08-29 19:54:36,1,5.0
31251,55505284,2017-08-29 19:54:34,NaT,1,NaN
31252,55506164,2017-08-29 20:10:01,NaT,1,NaN
31253,55513305,2017-08-29 22:21:13,NaT,1,NaN
31254,55515800,2017-08-29 23:18:48,NaT,1,NaN
31255,55516860,2017-08-29 23:47:24,NaT,1,NaN
31256,55532488,2017-08-30 07:30:34,NaT,1,NaN
31257,55556742,2017-08-30 14:43:38,NaT,1,NaN
31258,55557542,2017-08-30 14:55:32,NaT,1,NaN
31259,55557962,2017-08-30 15:01:21,NaT,1,NaN
31260,55562505,2017-08-30 16:07:55,NaT,1,NaN
31261,55563127,2017-08-30 16:18:44,NaT,1,NaN
31262,55563128,2017-08-30 16:18:44,NaT,1,NaN
31263,55566908,2017-08-30 17:13:56,NaT,1,NaN
31264,55566909,2017-08-30 17:13:56,NaT,1,NaN
31265,55580102,2017-08-30 21:01:58,NaT,1,NaN
31266,55581505,2017-08-30 21:29:11,NaT,1,NaN
31267,55593367,2017-08-31 02:32:18,NaT,1,NaN
31268,55616806,2017-08-31 12:12:09,NaT,1,NaN
31269,55633098,2017-08-31 16:25:14,2017-08-31 16:52:01,1,26.0
31270,55652974,2017-08-31 22:11:55,NaT,1,NaN

In [13]:
df = df.set_index(['opened'])
df = df.dropna()

KeyError: 'opened'