In [1]:
import ghdata
import pandas as pd
import numpy as np

ghtorrent = ghdata.GHTorrent("mysql+pymysql://root:ghtorrent@localhost/msr14")

In [3]:
contributors = ghtorrent.contributors("rails", "rails")
sums = contributors.sum()

contributors

,login,location,commits,pull_requests,issues,commit_comments,pull_request_comments,issue_comments,total
user_id,,,,,,,,,
69820,jeremy,"Scottsdale, AZ",3729.0,2.0,2.0,161.0,122.0,614.0,4630.0
175556,dhh,"Chicago, USA",3510.0,NaN,9.0,129.0,2.0,246.0,NaN
43434,josevalim,"Krak�w, Poland",3006.0,2.0,8.0,414.0,143.0,2003.0,5576.0
31607,tenderlove,Seattle,2794.0,NaN,4.0,253.0,106.0,1027.0,NaN
170069,rafaelfranca,"S�o Paulo, Brazil",1562.0,79.0,7.0,206.0,343.0,4176.0,6373.0
175103,fxn,Barcelona,1527.0,NaN,4.0,298.0,13.0,1022.0,NaN
30535,josh,"Chicago, IL",1253.0,9.0,4.0,151.0,11.0,153.0,1581.0
22053,spastorino,"Montevideo, Uruguay",1144.0,1.0,2.0,196.0,55.0,865.0,2263.0
170043,carlosantoniodasilva,"Rio do Sul, Santa Catarina, Brasil",1085.0,82.0,2.0,214.0,270.0,2482.0,4135.0
178284,lifo,London,923.0,NaN,NaN,48.0,NaN,2.0,NaN
17402,vijaydev,"Chennai, India",843.0,40.0,1.0,75.0,36.0,511.0,1506.0
56175,NZKoz,"Wellington, New Zealand",815.0,1.0,2.0,85.0,9.0,235.0,1147.0
2638,jonleighton,London,809.0,1.0,17.0,145.0,29.0,796.0,1797.0
76561,wycats,San Francisco,558.0,NaN,NaN,40.0,NaN,37.0,NaN
72858,technoweenie,"Rapid City, SD",468.0,NaN,1.0,4.0,NaN,2.0,NaN
169886,drogus,Warsaw,420.0,6.0,2.0,82.0,19.0,607.0,1136.0
28080,guilleiguaran,"Barranquilla, Colombia",379.0,142.0,26.0,64.0,58.0,926.0,1595.0
172474,jamis,"Caldwell, Idaho, USA",354.0,2.0,NaN,4.0,NaN,2.0,NaN
14527,senny,"Bern, Switzerland",349.0,167.0,60.0,32.0,105.0,1707.0,2420.0
20038,arunagw,Stockholm,322.0,345.0,22.0,35.0,21.0,1053.0,1798.0
170219,pixeltrix,"Coventry, UK",302.0,1.0,10.0,131.0,44.0,1155.0,1643.0
506603,WELTBBTP,None,301.0,NaN,NaN,NaN,NaN,NaN,NaN
180058,radar,"Melbourne, Australia",285.0,NaN,4.0,38.0,NaN,92.0,NaN
152882,tadast,"Central London, UK",258.0,3.0,4.0,3.0,1.0,28.0,297.0
173234,frodsan,"Lima, Per�",247.0,104.0,20.0,41.0,28.0,367.0,807.0
185659,robinroestenburg,Netherlands,243.0,1.0,NaN,NaN,NaN,4.0,NaN
190005,seckar,Northern California,231.0,NaN,NaN,NaN,NaN,NaN,NaN
27597,steveklabnik,"Santa Monica, CA",207.0,55.0,23.0,91.0,86.0,2743.0,3205.0
124155,amatsuda,Tokyo,202.0,75.0,6.0,24.0,2.0,49.0,358.0
170622,kennyj,"osaka, japan",195.0,194.0,43.0,20.0,10.0,786.0,1248.0
...,...,...,...,...,...,...,...,...,...
507678,josegit,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507679,darraghcurran,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507680,vomelchenko,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507681,KernComm,Hyderabad,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507682,rotor,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507683,leword,"Boulder, CO",NaN,NaN,NaN,1.0,NaN,NaN,NaN
507684,acook8103,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507686,olliesaunders,UK,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507687,tedhenry10,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507688,yawningman,,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507689,Yardboy,"Jacksonville, FL",NaN,NaN,NaN,1.0,NaN,NaN,NaN
507690,chicagogrooves,Chicago,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507691,ryanLonac,Seattle,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507692,testy-mctesterson-iseatz,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507693,yourewelcome,New York City,NaN,NaN,NaN,2.0,NaN,NaN,NaN
507694,nicb,"Rome, Italy and Copenhagen, Denmark",NaN,NaN,NaN,1.0,NaN,NaN,NaN
507698,paxx2,Mexico City,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507700,regabi,"San Francisco, CA",NaN,NaN,NaN,1.0,NaN,NaN,NaN
507703,TipMobileMirko,"Palo Alto, CA",NaN,NaN,NaN,1.0,NaN,NaN,NaN
507704,jon-eachscape,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507705,TinyFox,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507706,pesty,None,NaN,NaN,NaN,2.0,NaN,NaN,NaN
507707,seamxr,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507708,giro54,"Buenos Aires, Argentina",NaN,NaN,NaN,1.0,NaN,NaN,NaN
507712,cburnette,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507719,slezica,Argentina,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507720,damir,Croatia,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507722,ktacheny,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507726,oalca,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN
507727,bush,None,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [6]:
def classify(row):
    role = 'user'
    ratio = row / sums
    if (ratio['issue_comments'] > 0.05):
        role = 'tester'
    if (row['pull_requests'] >= 1 and row['commits'] == 0):
        role = 'rejected_contributor'
    if (row['pull_requests'] >= 1 and row['commits'] >= 1):
        role = 'contributor'
    if (ratio['pull_requests'] > 0.10 or ratio['commits'] > 0.01):
        role = 'major_contributor'
    if (ratio['commits'] > 0.02 or ratio['pull_request_comments'] > 0.15):
        role = 'maintainer'
    
    return pd.Series({'login': row['login'], 'role': role})
    
    

roles = contributors.apply(classify, axis=1)
roles

                            login               role
user_id
69820                      jeremy         maintainer
175556                        dhh         maintainer
43434                   josevalim         maintainer
31607                  tenderlove         maintainer
170069               rafaelfranca         maintainer
175103                        fxn         maintainer
30535                        josh         maintainer
22053                  spastorino         maintainer
170043       carlosantoniodasilva         maintainer
178284                       lifo         maintainer
17402                    vijaydev         maintainer
56175                       NZKoz         maintainer
2638                  jonleighton         maintainer
76561                      wycats  major_contributor
72858                technoweenie  major_contributor
169886                     drogus  major_contributor
28080               guilleiguaran  major_contributor
172474                      jamis        contributor
14527                       senny        contributor
20038                     arunagw        contributor
170219                  pixeltrix        contributor
506603                   WELTBBTP               user
180058                      radar               user
152882                     tadast        contributor
173234                    frodsan        contributor
185659           robinroestenburg        contributor
190005                     seckar               user
27597                steveklabnik        contributor
124155                   amatsuda        contributor
170622                     kennyj        contributor
...                           ...                ...
507678                    josegit               user
507679              darraghcurran               user
507680                vomelchenko               user
507681                   KernComm               user
507682                      rotor               user
507683                     leword               user
507684                  acook8103               user
507686              olliesaunders               user
507687                 tedhenry10               user
507688                 yawningman               user
507689                    Yardboy               user
507690             chicagogrooves               user
507691                  ryanLonac               user
507692   testy-mctesterson-iseatz               user
507693               yourewelcome               user
507694                       nicb               user
507698                      paxx2               user
507700                     regabi               user
507703             TipMobileMirko               user
507704              jon-eachscape               user
507705                    TinyFox               user
507706                      pesty               user
507707                     seamxr               user
507708                     giro54               user
507712                  cburnette               user
507719                    slezica               user
507720                      damir               user
507722                   ktacheny               user
507726                      oalca               user
507727                       bush               user

[7749 rows x 2 columns]

user_id
136322           markstory
137012              phpnut
269456           nateabele
505796            EXPAMFJE
23445              lorenzo
136448               ADmad
505801            IIMXTENO
136342              ceeram
114050         dereuromark
81271               AD7six
11106              felixge
5258        justinledwards
25678          predominant
505832            LCQSGUWF
34963              jrbasso
136441             tim-kos
442390               renan
45385              jperras
56386           richardjoo
17542              rchavik
38498                shama
47972          renansaddam
137843            ravage84
136426          dogmatic69
505804            XXMQSJYQ
113125               majna
115080              tPl0ch
505811            MYKVLWDY
117845              Phally
505843            IMLSICOI
                ...
143582    robarwebservices
143749           daigo2010
143777           henryturk
143785          xavier83ar
143822              monsat
143823             rycarus
144034           veganista
144049              vindia
144132             mdunham
144159              voidet
146000                 h3u
147584       carstenkiefer
148099          cvandeplas
148264            func0der
148434               jinhr
148571              lsiden
149036           soulraven
158810            steffann
168640            williamn
269778               Adduc
294161    wouterverweirder
298688                 513
456630             flotwig
476312       parkerbossier
499568      sebastienbarre
506192               hsubu
507381           biesbjerg
507385             kingbet
507386              grobux
507394          default007
Name: login, dtype: object
user_id
136322              Toronto, Ontario
137012                          None
269456              Philadelphia, PA
505796                          None
23445             Caracas, Venezuela
136448                          None
505801                          None
136342    Amsterdam, The Netherlands
114050              Munich - Germany
81271                          Spain
11106                Berlin, Germany
5258                        Oklahoma
25678                   Tokyo, Japan
505832                          None
34963              Aventura, FL, USA
136441                Berlin/Germany
442390    Amsterdam, The Netherlands
45385                Toronto, Canada
56386          Portland, Oregon, USA
17542             Jakarta, Indonesia
38498                       Napa, CA
47972     Amsterdam, The Netherlands
137843            Basel, Switzerland
136426                       B97, UK
505804                          None
113125             Varazdin, Croatia
115080             Mannheim, Germany
505811                          None
117845                   Netherlands
505843                          None
                     ...
143582                          None
143749                          None
143777                          None
143785           Santa Fe, Argentina
143822                 Tokyo , JAPAN
143823                          None
144034                          None
144049                     Amsterdam
144132               Tulsa, Oklahoma
144159           Brisbane, Australia
146000               Cologne/Germany
147584                       Germany
148099                       Belgium
148264                       Germany
148434                          None
148571            Ann Arbor, MI, USA
149036              Campulung Muscel
158810                     Apeldoorn
168640
269778                    Joliet, IL
294161                          None
298688                          None
456630                       Georgia
476312                Pittsburgh, PA
499568                    Albany, NY
506192                          None
507381               Odense, Denmark
507385                          None
507386                          None
507394                          None
Name: location, dtype: object
user_id
136322    3968
137012    1564
269456    1042
505796     970
23445      900
136448     387
505801     288
136342     247
114050     224
81271      204
11106      148
5258       138
25678      137
505832     130
34963      119
136441     119
442390     118
45385       98
56386       97
17542       92
38498       81
47972       77
137843      66
136426      43
505804      42
113125      41
115080      35
505811      35
117845      31
505843      31
          ...
143582     NaN
143749     NaN
143777     NaN
143785     NaN
143822     NaN
143823     NaN
144034     NaN
144049     NaN
144132     NaN
144159     NaN
146000     NaN
147584     NaN
148099     NaN
148264     NaN
148434     NaN
148571     NaN
149036     NaN
158810     NaN
168640     NaN
269778     NaN
294161     NaN
298688     NaN
456630     NaN
476312     NaN
499568     NaN
506192     NaN
507381     NaN
507385     NaN
507386     NaN
507394     NaN
Name: commits, dtype: object
user_id
136322     60
137012    NaN
269456    NaN
505796    NaN
23445      14
136448     70
505801    NaN
136342     35
114050    140
81271       8
11106     NaN
5258      NaN
25678       3
505832    NaN
34963       3
136441    NaN
442390      6
45385     NaN
56386     NaN
17542      17
38498      90
47972     NaN
137843     40
136426     37
505804    NaN
113125     38
115080     26
505811    NaN
117845     20
505843    NaN
         ...
143582    NaN
143749    NaN
143777    NaN
143785    NaN
143822    NaN
143823    NaN
144034    NaN
144049    NaN
144132    NaN
144159    NaN
146000    NaN
147584    NaN
148099    NaN
148264    NaN
148434    NaN
148571    NaN
149036    NaN
158810    NaN
168640      1
269778      1
294161    NaN
298688    NaN
456630    NaN
476312    NaN
499568    NaN
506192    NaN
507381    NaN
507385    NaN
507386    NaN
507394    NaN
Name: pull_requests, dtype: object
user_id
136322    None
137012    None
269456    None
505796    None
23445     None
136448    None
505801    None
136342    None
114050    None
81271     None
11106     None
5258      None
25678     None
505832    None
34963     None
136441    None
442390    None
45385     None
56386     None
17542     None
38498     None
47972     None
137843    None
136426    None
505804    None
113125    None
115080    None
505811    None
117845    None
505843    None
          ...
143582    None
143749    None
143777    None
143785    None
143822    None
143823    None
144034    None
144049    None
144132    None
144159    None
146000    None
147584    None
148099    None
148264    None
148434    None
148571    None
149036    None
158810    None
168640    None
269778    None
294161    None
298688    None
456630    None
476312    None
499568    None
506192    None
507381    None
507385    None
507386    None
507394    None
Name: issues, dtype: object
user_id
136322    158
137012    NaN
269456    NaN
505796    NaN
23445      41
136448     79
505801    NaN
136342     46
114050     39
81271      14
11106     NaN
5258      NaN
25678       1
505832    NaN
34963      10
136441    NaN
442390     18
45385     NaN
56386     NaN
17542       3
38498       2
47972     NaN
137843     15
136426    NaN
505804    NaN
113125      4
115080      7
505811    NaN
117845      4
505843    NaN
         ...
143582    NaN
143749    NaN
143777    NaN
143785    NaN
143822    NaN
143823    NaN
144034    NaN
144049    NaN
144132      1
144159      1
146000    NaN
147584    NaN
148099      1
148264      3
148434      2
148571      2
149036    NaN
158810      1
168640    NaN
269778    NaN
294161      1
298688      2
456630      1
476312      1
499568      2
506192    NaN
507381      2
507385      1
507386      2
507394      1
Name: commit_comments, dtype: object
user_id
136322    718
137012    NaN
269456    NaN
505796    NaN
23445     265
136448    245
505801    NaN
136342     59
114050    229
81271      28
11106     NaN
5258      NaN
25678     NaN
505832    NaN
34963      54
136441    NaN
442390     29
45385     NaN
56386     NaN
17542      21
38498      15
47972      19
137843     72
136426      7
505804    NaN
113125     10
115080     15
505811    NaN
117845     26
505843    NaN
         ...
143582    NaN
143749    NaN
143777    NaN
143785    NaN
143822    NaN
143823    NaN
144034    NaN
144049    NaN
144132      1
144159    NaN
146000    NaN
147584    NaN
148099    NaN
148264    NaN
148434    NaN
148571    NaN
149036    NaN
158810    NaN
168640    NaN
269778    NaN
294161    NaN
298688    NaN
456630    NaN
476312    NaN
499568    NaN
506192    NaN
507381    NaN
507385    NaN
507386    NaN
507394    NaN
Name: pull_request_comments, dtype: object
user_id
136322    1668
137012     NaN
269456     NaN
505796     NaN
23445      570
136448     652
505801     NaN
136342     258
114050     523
81271      117
11106      NaN
5258       NaN
25678       13
505832     NaN
34963       68
136441     NaN
442390      31
45385      NaN
56386      NaN
17542      133
38498       52
47972       66
137843     171
136426      44
505804     NaN
113125      34
115080      64
505811     NaN
117845     127
505843     NaN
          ...
143582       1
143749       1
143777       1
143785       4
143822       1
143823       1
144034       1
144049       1
144132       4
144159       1
146000       3
147584       4
148099     NaN
148264     NaN
148434     NaN
148571     NaN
149036       1
158810     NaN
168640       1
269778     NaN
294161     NaN
298688     NaN
456630     NaN
476312     NaN
499568     NaN
506192       2
507381     NaN
507385     NaN
507386     NaN
507394     NaN
Name: issue_comments, dtype: object
user_id
136322    None
137012    None
269456    None
505796    None
23445     None
136448    None
505801    None
136342    None
114050    None
81271     None
11106     None
5258      None
25678     None
505832    None
34963     None
136441    None
442390    None
45385     None
56386     None
17542     None
38498     None
47972     None
137843    None
136426    None
505804    None
113125    None
115080    None
505811    None
117845    None
505843    None
          ...
143582    None
143749    None
143777    None
143785    None
143822    None
143823    None
144034    None
144049    None
144132    None
144159    None
146000    None
147584    None
148099    None
148264    None
148434    None
148571    None
149036    None
158810    None
168640    None
269778    None
294161    None
298688    None
456630    None
476312    None
499568    None
506192    None
507381    None
507385    None
507386    None
507394    None
Name: total, dtype: object

,login,location,commits,pull_requests,issues,commit_comments,pull_request_comments,issue_comments,total
user_id,,,,,,,,,
136322,markstory,"Toronto, Ontario",3968.0,60.0,None,158.0,718.0,1668.0,None
137012,phpnut,None,1564.0,NaN,None,NaN,NaN,NaN,None
269456,nateabele,"Philadelphia, PA",1042.0,NaN,None,NaN,NaN,NaN,None
505796,EXPAMFJE,None,970.0,NaN,None,NaN,NaN,NaN,None
23445,lorenzo,"Caracas, Venezuela",900.0,14.0,None,41.0,265.0,570.0,None
136448,ADmad,None,387.0,70.0,None,79.0,245.0,652.0,None
505801,IIMXTENO,None,288.0,NaN,None,NaN,NaN,NaN,None
136342,ceeram,"Amsterdam, The Netherlands",247.0,35.0,None,46.0,59.0,258.0,None
114050,dereuromark,Munich - Germany,224.0,140.0,None,39.0,229.0,523.0,None
81271,AD7six,Spain,204.0,8.0,None,14.0,28.0,117.0,None
11106,felixge,"Berlin, Germany",148.0,NaN,None,NaN,NaN,NaN,None
5258,justinledwards,Oklahoma,138.0,NaN,None,NaN,NaN,NaN,None
25678,predominant,"Tokyo, Japan",137.0,3.0,None,1.0,NaN,13.0,None
505832,LCQSGUWF,None,130.0,NaN,None,NaN,NaN,NaN,None
34963,jrbasso,"Aventura, FL, USA",119.0,3.0,None,10.0,54.0,68.0,None
136441,tim-kos,Berlin/Germany,119.0,NaN,None,NaN,NaN,NaN,None
442390,renan,"Amsterdam, The Netherlands",118.0,6.0,None,18.0,29.0,31.0,None
45385,jperras,"Toronto, Canada",98.0,NaN,None,NaN,NaN,NaN,None
56386,richardjoo,"Portland, Oregon, USA",97.0,NaN,None,NaN,NaN,NaN,None
17542,rchavik,"Jakarta, Indonesia",92.0,17.0,None,3.0,21.0,133.0,None
38498,shama,"Napa, CA",81.0,90.0,None,2.0,15.0,52.0,None
47972,renansaddam,"Amsterdam, The Netherlands",77.0,NaN,None,NaN,19.0,66.0,None
137843,ravage84,"Basel, Switzerland",66.0,40.0,None,15.0,72.0,171.0,None
136426,dogmatic69,"B97, UK",43.0,37.0,None,NaN,7.0,44.0,None
505804,XXMQSJYQ,None,42.0,NaN,None,NaN,NaN,NaN,None
113125,majna,"Varazdin, Croatia",41.0,38.0,None,4.0,10.0,34.0,None
115080,tPl0ch,"Mannheim, Germany",35.0,26.0,None,7.0,15.0,64.0,None
505811,MYKVLWDY,None,35.0,NaN,None,NaN,NaN,NaN,None
117845,Phally,Netherlands,31.0,20.0,None,4.0,26.0,127.0,None
505843,IMLSICOI,None,31.0,NaN,None,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...
143582,robarwebservices,None,NaN,NaN,None,NaN,NaN,1.0,None
143749,daigo2010,None,NaN,NaN,None,NaN,NaN,1.0,None
143777,henryturk,None,NaN,NaN,None,NaN,NaN,1.0,None
143785,xavier83ar,"Santa Fe, Argentina",NaN,NaN,None,NaN,NaN,4.0,None
143822,monsat,"Tokyo , JAPAN",NaN,NaN,None,NaN,NaN,1.0,None
143823,rycarus,None,NaN,NaN,None,NaN,NaN,1.0,None
144034,veganista,None,NaN,NaN,None,NaN,NaN,1.0,None
144049,vindia,Amsterdam,NaN,NaN,None,NaN,NaN,1.0,None
144132,mdunham,"Tulsa, Oklahoma",NaN,NaN,None,1.0,1.0,4.0,None
144159,voidet,"Brisbane, Australia",NaN,NaN,None,1.0,NaN,1.0,None
146000,h3u,Cologne/Germany,NaN,NaN,None,NaN,NaN,3.0,None
147584,carstenkiefer,Germany,NaN,NaN,None,NaN,NaN,4.0,None
148099,cvandeplas,Belgium,NaN,NaN,None,1.0,NaN,NaN,None
148264,func0der,Germany,NaN,NaN,None,3.0,NaN,NaN,None
148434,jinhr,None,NaN,NaN,None,2.0,NaN,NaN,None
148571,lsiden,"Ann Arbor, MI, USA",NaN,NaN,None,2.0,NaN,NaN,None
149036,soulraven,Campulung Muscel,NaN,NaN,None,NaN,NaN,1.0,None
158810,steffann,Apeldoorn,NaN,NaN,None,1.0,NaN,NaN,None
168640,williamn,,NaN,1.0,None,NaN,NaN,1.0,None
269778,Adduc,"Joliet, IL",NaN,1.0,None,NaN,NaN,NaN,None
294161,wouterverweirder,None,NaN,NaN,None,1.0,NaN,NaN,None
298688,513,None,NaN,NaN,None,2.0,NaN,NaN,None
456630,flotwig,Georgia,NaN,NaN,None,1.0,NaN,NaN,None
476312,parkerbossier,"Pittsburgh, PA",NaN,NaN,None,1.0,NaN,NaN,None
499568,sebastienbarre,"Albany, NY",NaN,NaN,None,2.0,NaN,NaN,None
506192,hsubu,None,NaN,NaN,None,NaN,NaN,2.0,None
507381,biesbjerg,"Odense, Denmark",NaN,NaN,None,2.0,NaN,NaN,None
507385,kingbet,None,NaN,NaN,None,1.0,NaN,NaN,None
507386,grobux,None,NaN,NaN,None,2.0,NaN,NaN,None
507394,default007,None,NaN,NaN,None,1.0,NaN,NaN,None